// lang.ts — багатомовність для Redmine by DeVylM + Activity ID
import * as vscode from 'vscode'

const translations: Record<string, Record<string, string>> = {
	en: {
		startTracking: '▶️ Start Tracking',
		stopTracking: '⏹ Stop Tracking',
		setIssue: '📝 Set Active Issue',
		setIssuePrompt: 'Enter Redmine Issue ID',
		setIssueConfirm: 'Active issue set to',
		enterTime: '⏱ Enter Manual Time',
		enterTimePrompt: 'Enter time (e.g. 1.5 for 1 hour 30 mins)',
		manualTimeSet: 'Manual time set:',
		sendTime: '📤 Send Time to Redmine',
		timeSent: 'Time entry sent',
		sendError: 'Failed to send time. Status:',
		requestError: 'Request error:',
		noIssue: 'No active issue',
		tooltip: 'Click to open action menu',
		placeholder: 'What do you want to do?',
		fetchingIssues: 'Fetching issues...',
		noIssuesFound: 'No issues found.',
		chooseIssue: 'Choose an issue to track',
		chooseActivity: 'Choose activity for time entry',
		setActivity: '⚙️ Set Activity ID',
		activitySet: 'Activity set to:',
	},
	uk: {
		startTracking: '▶️ Почати трекінг',
		stopTracking: '⏹ Зупинити трекінг',
		setIssue: '📝 Встановити активну задачу',
		setIssuePrompt: 'Введи ID задачі Redmine',
		setIssueConfirm: 'Задача встановлена як активна:',
		enterTime: '⏱ Вказати час вручну',
		enterTimePrompt: 'Введи час (наприклад, 1.5 = 1 год 30 хв)',
		manualTimeSet: 'Встановлено час вручну:',
		sendTime: '📤 Відправити час у Redmine',
		timeSent: 'Час надіслано',
		sendError: 'Помилка відправки часу. Статус:',
		requestError: 'Помилка запиту:',
		noIssue: 'Немає активної задачі',
		tooltip: 'Клікни для меню дій',
		placeholder: 'Що бажаєш зробити?',
		fetchingIssues: 'Завантаження задач...',
		noIssuesFound: 'Задач не знайдено.',
		chooseIssue: 'Вибери задачу для трекінгу',
		chooseActivity: 'Вибери активність для обліку часу',
		setActivity: '⚙️ Встановити Activity ID',
		activitySet: 'Активність встановлена:',
	},
	ru: {
		startTracking: '▶️ Начать трекинг',
		stopTracking: '⏹ Остановить трекинг',
		setIssue: '📝 Установить активную задачу',
		setIssuePrompt: 'Введите ID задачи Redmine',
		setIssueConfirm: 'Активная задача установлена:',
		enterTime: '⏱ Ввести время вручную',
		enterTimePrompt: 'Введите время (например, 1.5 = 1 час 30 минут)',
		manualTimeSet: 'Время вручную установлено:',
		sendTime: '📤 Отправить время в Redmine',
		timeSent: 'Время успешно отправлено',
		sendError: 'Ошибка отправки времени. Статус:',
		requestError: 'Ошибка запроса:',
		noIssue: 'Нет активной задачи',
		tooltip: 'Кликните для меню действий',
		placeholder: 'Что вы хотите сделать?',
		fetchingIssues: 'Загрузка задач...',
		noIssuesFound: 'Задачи не найдены.',
		chooseIssue: 'Выберите задачу для отслеживания',
		chooseActivity: 'Выберите активность для учета времени',
		setActivity: '⚙️ Установить Activity ID',
		activitySet: 'Активность установлена:',
	},
	pl: {
		startTracking: '▶️ Rozpocznij śledzenie',
		stopTracking: '⏹ Zatrzymaj śledzenie',
		setIssue: '📝 Ustaw aktywne zadanie',
		setIssuePrompt: 'Wpisz ID zadania Redmine',
		setIssueConfirm: 'Ustawiono aktywne zadanie:',
		enterTime: '⏱ Wprowadź czas ręcznie',
		enterTimePrompt: 'Wpisz czas (np. 1.5 = 1 godzina 30 minut)',
		manualTimeSet: 'Ustawiono ręczny czas:',
		sendTime: '📤 Wyślij czas do Redmine',
		timeSent: 'Czas wysłany',
		sendError: 'Błąd wysyłania czasu. Status:',
		requestError: 'Błąd żądania:',
		noIssue: 'Brak aktywnego zadania',
		tooltip: 'Kliknij, aby otworzyć menu',
		placeholder: 'Co chcesz zrobić?',
		fetchingIssues: 'Pobieranie zadań...',
		noIssuesFound: 'Nie znaleziono zadań.',
		chooseIssue: 'Wybierz zadanie do śledzenia',
		chooseActivity: 'Wybierz aktywność do rejestru czasu',
		setActivity: '⚙️ Ustaw ID aktywności',
		activitySet: 'Aktywność ustawiona:',
	},
}

const lang = vscode?.env?.language?.substring(0, 2) || 'en'

export function t(key: string): string {
	return translations[lang]?.[key] || translations['en'][key] || key
}
